#! /usr/bin/env python
'''
################################################################
# Prune away branches of a flat root tree to produce an ntuple #
################################################################
'''
import argparse
import os
import sys
from array import array
try:
    from ROOT import TFile, TNtuple, TChain
except ImportError:
    print "Cant find root lib is it in $PYTHONPATH?"
    sys.exit()

def make_ntup(file_name, tree_name, branches, outfile, n_events, new_tree_name):
    '''
    make ntp
    '''
    if new_tree_name == "":
        new_tree_name = tree_name

    print file_name

    # Get the event tree
    tree = TChain(tree_name)
    tree.Add(file_name)
    if not tree:
        print "Error: No tree named %s in %s" %(tree_name, file_name)
        sys.exit()

    # Check branches exist
    branches_avail = [x.GetName() for x in tree.GetListOfBranches()]
    for branch in branches:
        if not branch in branches_avail:
            print "Error branch '%s' not a branch in input tree" %(branch)
            print "Branches available are: \n"
            print "\t".join(branches_avail)
            sys.exit()

    # output
    out_file = TFile(outfile, "RECREATE")
    ntp = TNtuple(new_tree_name, "", ":".join(branches))

    if n_events < 0:
        n_events = tree.GetEntries()

    # loop over events and fill the branches of new ntuple
    for index, entry in enumerate(tree):
        if index > n_events:
            break
        vals = array('f', [entry.__getattr__(b) for b in branches])
        ntp.Fill(vals)

        if index % 100000 == 0:
            print index, "/", n_events
    # Save
    out_file.cd()
    ntp.Write()
    out_file.Close()

    print "Written %i entries of branch(es) '%s' \nto tree %s  \nin file %s"\
        %(n_events, ":".join(branches), new_tree_name, outfile)

def main(args):
    '''
    load args
    '''
    parser = argparse.ArgumentParser()
    parser.add_argument('filename', type=str, )
    parser.add_argument('-treename', metavar='-t', type=str, default="output")
    parser.add_argument('-newtreename', type=str, default="")
    parser.add_argument('branches', nargs="+", type=str)
    parser.add_argument('-outfile', metavar='-o', type=str, default="")
    parser.add_argument('-nevents', metavar='-nev', type=int, default=-1)
    args = parser.parse_args(args)

    if args.outfile == "":
        outfile = os.path.split(args.filename)[1]
        outfile = os.path.splitext(outfile)[0]
        outfile += "_oxsx.root"
        args.outfile = outfile
    make_ntup(args.filename, args.treename, args.branches, \
        args.outfile, args.nevents, args.newtreename)

if __name__ == "__main__":
    main(sys.argv[1:]) #callable from command line or by importing
