#!python
Import('env')
Import('lib')

# make the object files
unit_test_files = Glob("*/*.cpp") + Glob("*.cpp")

unit_tests      = [env.Object(x) for x in unit_test_files]
unit_test_executible = env.Program("#/test/RunUnits", 
                                       source = [unit_tests, lib],
                                       )

env.Alias("units", unit_test_executible)
